/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lenovo
 */
import java.sql.*;
import javax.swing.*;
public class addbirdwatcher extends javax.swing.JFrame {
    Connection con;
    PreparedStatement pst;
    /**
     * Creates new form addbirdwatcher
     */
    public addbirdwatcher() {
        initComponents();
        con=SQLCON.connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblNIC = new javax.swing.JLabel();
        lblURN = new javax.swing.JLabel();
        lblWPA = new javax.swing.JLabel();
        txtNIC = new javax.swing.JTextField();
        txtURN = new javax.swing.JTextField();
        txtWPA = new javax.swing.JTextField();
        btnGURN = new javax.swing.JButton();
        btnABW = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 100)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Add Bird Watcher");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 90, 880, 100));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51,120));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNIC.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lblNIC.setForeground(new java.awt.Color(255, 255, 255));
        lblNIC.setText("NIC");
        jPanel2.add(lblNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        lblURN.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lblURN.setForeground(new java.awt.Color(255, 255, 255));
        lblURN.setText("URN");
        jPanel2.add(lblURN, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        lblWPA.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lblWPA.setForeground(new java.awt.Color(255, 255, 255));
        lblWPA.setText("Wildlife Protected Area");
        jPanel2.add(lblWPA, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        txtNIC.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jPanel2.add(txtNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 330, 50));

        txtURN.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jPanel2.add(txtURN, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 330, 50));

        txtWPA.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jPanel2.add(txtWPA, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, 330, 50));

        btnGURN.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnGURN.setText("Genarate URN");
        btnGURN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGURNActionPerformed(evt);
            }
        });
        jPanel2.add(btnGURN, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 180, 50));

        btnABW.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnABW.setText("Add Bird Watcher");
        btnABW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnABWActionPerformed(evt);
            }
        });
        jPanel2.add(btnABW, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 390, 210, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 320, 780, 500));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(204, 255, 204));
        jLabel1.setForeground(new java.awt.Color(204, 255, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Documents\\NetBeansProjects\\BCMS\\images\\bg11.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 450, 700));

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Documents\\NetBeansProjects\\BCMS\\images\\left-arrow.png")); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Documents\\NetBeansProjects\\BCMS\\images\\grasss.png")); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-110, 750, 580, 310));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 1080));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Documents\\NetBeansProjects\\BCMS\\images\\pppppppppppp (1).jpg")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(461, -4, 1460, 1090));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGURNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGURNActionPerformed
        // TODO add your handling code here:
        int genarate_int=(int)Math.floor(Math.random() * (888888888-120+1)+33);
        txtURN.setText(Integer.toString(genarate_int));
        
    }//GEN-LAST:event_btnGURNActionPerformed

    private void btnABWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnABWActionPerformed
        // TODO add your handling code here:
        String sql="INSERT INTO birdwatcher Values(?,?,?)";
        try{
            pst=con.prepareStatement(sql);
            pst.setString(1,txtNIC.getText());
            pst.setString(2,txtURN.getText());
            pst.setString(3,txtWPA.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null,"Successfully Added");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_btnABWActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.toBack();
        Login lg = new Login();
        lg.setVisible(true);
        lg.toFront();
        this.hide();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addbirdwatcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addbirdwatcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addbirdwatcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addbirdwatcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addbirdwatcher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnABW;
    private javax.swing.JButton btnGURN;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblNIC;
    private javax.swing.JLabel lblURN;
    private javax.swing.JLabel lblWPA;
    private javax.swing.JTextField txtNIC;
    private javax.swing.JTextField txtURN;
    private javax.swing.JTextField txtWPA;
    // End of variables declaration//GEN-END:variables
}
