
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author manuja
 */
import java.sql.*;
import javax.swing.*;
public class BirdWatcherLogin extends javax.swing.JFrame {
    
    Connection con;
    PreparedStatement pat;

    /**
     * Creates new form BirdWatcherLogin
     */
    public BirdWatcherLogin() {
        initComponents();
        con=SQLCON.connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnback = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblBWT = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();
        txturn = new javax.swing.JTextField();
        txtNIC = new javax.swing.JTextField();
        lblurn = new javax.swing.JLabel();
        lblNIC = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bird Watcher Login Page");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnback.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Documents\\NetBeansProjects\\BCMS\\images\\left-arrow.png")); // NOI18N
        btnback.setText("Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        getContentPane().add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 110, 30));

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 3020, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Documents\\NetBeansProjects\\BCMS\\images\\bg5.png")); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, -150, 520, 1090));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Documents\\NetBeansProjects\\BCMS\\images\\grasss.png")); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 690, 570, 390));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 1080));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBWT.setFont(new java.awt.Font("Bookman Old Style", 1, 90)); // NOI18N
        lblBWT.setForeground(new java.awt.Color(255, 255, 255));
        lblBWT.setText("Bird Watcher Login");
        jPanel3.add(lblBWT, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 940, 110));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51,180));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogin.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel4.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 307, 110, 50));

        txturn.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txturnActionPerformed(evt);
            }
        });
        jPanel4.add(txturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 370, 60));

        txtNIC.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jPanel4.add(txtNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 370, 60));

        lblurn.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lblurn.setForeground(new java.awt.Color(255, 255, 255));
        lblurn.setText("URN");
        jPanel4.add(lblurn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        lblNIC.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lblNIC.setForeground(new java.awt.Color(255, 255, 255));
        lblNIC.setText("NIC");
        jPanel4.add(lblNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, 680, 400));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Documents\\NetBeansProjects\\BCMS\\images\\qq.jpg")); // NOI18N
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 1080));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 1400, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txturnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txturnActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
                try{
                    String sql = "Select * from birdwatcher where nic=? and urn=?";
                    PreparedStatement pst = con.prepareStatement(sql);
                    pst.setString(1,txtNIC.getText());
                    pst.setString(2,txturn.getText());
                    ResultSet rs =pst.executeQuery();
                    if(rs.next()){
                        JOptionPane.showMessageDialog(null,"NIC and URN Matched");
                        birdwatcher_dashboard bd = new birdwatcher_dashboard();
                        bd.setVisible(true);
                        setVisible(false);
                    }else{
                        JOptionPane.showMessageDialog(null,"Incorrect NIC or URN");
                        txtNIC.setText("");
                        txturn.setText("");
                    }con.close();
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null,e);
                }
        
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        this.toBack();
        Login lg = new Login();
        lg.setVisible(true);
        lg.toFront();
        this.hide();
    }//GEN-LAST:event_btnbackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BirdWatcherLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BirdWatcherLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BirdWatcherLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BirdWatcherLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BirdWatcherLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnback;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblBWT;
    private javax.swing.JLabel lblNIC;
    private javax.swing.JLabel lblurn;
    private javax.swing.JTextField txtNIC;
    private javax.swing.JTextField txturn;
    // End of variables declaration//GEN-END:variables
}
