/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lenovo
 */
import java.sql.*;
import javax.swing.*;
public class birdwatcher_dashboard extends javax.swing.JFrame {
    
    Connection con;
    PreparedStatement pst;
    /**
     * Creates new form birdwatcher_dashboard
     */
    public birdwatcher_dashboard() {
        initComponents();
        con=SQLCON.connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnclear = new javax.swing.JButton();
        btnadd = new javax.swing.JButton();
        txtpopulation = new javax.swing.JTextField();
        txtsize = new javax.swing.JTextField();
        txtcolour = new javax.swing.JTextField();
        txtwpa = new javax.swing.JTextField();
        lblpopulation = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblcolour = new javax.swing.JLabel();
        lblwpa = new javax.swing.JLabel();
        lblSN1 = new javax.swing.JLabel();
        txtSN1 = new javax.swing.JTextField();
        btndelete = new javax.swing.JButton();
        btnupdate1 = new javax.swing.JButton();
        btnsearch = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnbacktohome = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1510, 470, -1, -1));

        jPanel3.setBackground(new java.awt.Color(102, 102, 102,180));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnclear.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnclear.setText("Clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        jPanel3.add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 560, 100, 50));

        btnadd.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnadd.setText("Add");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });
        jPanel3.add(btnadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, 100, 50));

        txtpopulation.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txtpopulation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpopulationActionPerformed(evt);
            }
        });
        jPanel3.add(txtpopulation, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, 350, 60));

        txtsize.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txtsize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsizeActionPerformed(evt);
            }
        });
        jPanel3.add(txtsize, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 350, 60));

        txtcolour.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txtcolour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcolourActionPerformed(evt);
            }
        });
        jPanel3.add(txtcolour, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 350, 60));

        txtwpa.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txtwpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtwpaActionPerformed(evt);
            }
        });
        jPanel3.add(txtwpa, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 350, 60));

        lblpopulation.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lblpopulation.setForeground(new java.awt.Color(255, 255, 255));
        lblpopulation.setText("Population");
        jPanel3.add(lblpopulation, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Size");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        lblcolour.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lblcolour.setForeground(new java.awt.Color(255, 255, 255));
        lblcolour.setText("Colour");
        jPanel3.add(lblcolour, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        lblwpa.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lblwpa.setForeground(new java.awt.Color(255, 255, 255));
        lblwpa.setText("WPA");
        jPanel3.add(lblwpa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        lblSN1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lblSN1.setForeground(new java.awt.Color(255, 255, 255));
        lblSN1.setText("Scientific Name");
        jPanel3.add(lblSN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        txtSN1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txtSN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSN1ActionPerformed(evt);
            }
        });
        jPanel3.add(txtSN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 350, 60));

        btndelete.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        jPanel3.add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 560, 110, 50));

        btnupdate1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnupdate1.setText("Update");
        btnupdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdate1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnupdate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 560, 110, 50));

        btnsearch.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnsearch.setText("Search");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });
        jPanel3.add(btnsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 570, 90, 40));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, 740, 690));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 100)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Add New Bird Record");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, -1, -1));

        btnbacktohome.setBackground(new java.awt.Color(255, 255, 255));
        btnbacktohome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnbacktohome.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Documents\\NetBeansProjects\\BCMS\\images\\left-arrow.png")); // NOI18N
        btnbacktohome.setText("Back");
        btnbacktohome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbacktohomeActionPerformed(evt);
            }
        });
        jPanel2.add(btnbacktohome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Documents\\NetBeansProjects\\BCMS\\images\\5.jpg")); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, -4, 1920, 1080));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        setSize(new java.awt.Dimension(1938, 1127));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtwpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtwpaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtwpaActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
        String sql="INSERT INTO bird Values(?,?,?,?,?)";
        try{
            pst=con.prepareStatement(sql);
            pst.setString(1,txtSN1.getText());
            pst.setString(2,txtwpa.getText());
            pst.setString(3,txtcolour.getText());
            pst.setString(4,txtsize.getText());
            pst.setString(5,txtpopulation.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null,"Successfully Added");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);//instead of e add a msg "System is unavailable"
        }
    }//GEN-LAST:event_btnaddActionPerformed

    private void txtsizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsizeActionPerformed

    private void txtpopulationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpopulationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpopulationActionPerformed

    private void txtcolourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcolourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcolourActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        txtSN1.setText("");
        txtwpa.setText("");
        txtcolour.setText("");
        txtsize.setText("");
        txtpopulation.setText("");
    }//GEN-LAST:event_btnclearActionPerformed

    private void btnbacktohomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbacktohomeActionPerformed
        // TODO add your handling code here:
        this.toBack();
        Login lg = new Login();
        lg.setVisible(true);
        lg.toFront();
        this.hide();
    }//GEN-LAST:event_btnbacktohomeActionPerformed

    private void txtSN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSN1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSN1ActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        try{
            pst=con.prepareStatement("delete from bird where scientific_name=?");
            pst.setString(1,txtSN1.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"Deleted");
            
    }   catch(Exception e){
         JOptionPane.showMessageDialog(null,e);
    }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnupdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdate1ActionPerformed
        // TODO add your handling code here:
             try{
         String value1=txtSN1.getText();
         String value2=txtwpa.getText();
         String value3=txtpopulation.getText();
         String value4=txtcolour.getText();
         String value5=txtsize.getText();
         
         String Sql ="Update bird set scientific_name='"+value1+"',wildlife_protected_area='"+value2+"',population='"+value3+"',colour='"+value4+"',size='"+value5+"' where scientific_name='"+value1+"'";
         pst=con.prepareStatement(Sql);
         pst.execute();
         JOptionPane.showMessageDialog(null,"Update");
     }catch(Exception e){
         JOptionPane.showMessageDialog(null,e);
     }
    }//GEN-LAST:event_btnupdate1ActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here:
        try{
           Statement st=con.createStatement();
           String scientific_name=txtSN1.getText();
           String sql ="SELECT * FROM bird WHERE scientific_name='"+scientific_name+"'";
           ResultSet rs=st.executeQuery(sql);
           
           if (rs.next()==false)
           {
              JOptionPane.showMessageDialog(null,"Invalid name"); 
           }
           
           
           String wildlife_protected_area=rs.getString ("wildlife_protected_area");
           txtwpa.setText(wildlife_protected_area);
           
           String population =rs.getString ("population");
           txtpopulation.setText(population);
           
           String colour =rs.getString ("colour");
           txtcolour.setText(colour);
           
           String size=rs.getString("size");
           txtsize.setText(size);
           
           
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);  
            //LblMessage.setText("Error");
        }
            
    
        
    }//GEN-LAST:event_btnsearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(birdwatcher_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(birdwatcher_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(birdwatcher_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(birdwatcher_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new birdwatcher_dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnbacktohome;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton btnupdate1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblSN1;
    private javax.swing.JLabel lblcolour;
    private javax.swing.JLabel lblpopulation;
    private javax.swing.JLabel lblwpa;
    private javax.swing.JTextField txtSN1;
    private javax.swing.JTextField txtcolour;
    private javax.swing.JTextField txtpopulation;
    private javax.swing.JTextField txtsize;
    private javax.swing.JTextField txtwpa;
    // End of variables declaration//GEN-END:variables
}
