/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lenovo
 */
import java.sql.*;
import javax.swing.*;
public class department_officer extends javax.swing.JFrame {
        Connection con;
    PreparedStatement pst;

    /**
     * Creates new form department_officer
     */
    public department_officer() {
        initComponents();
        con=SQLCON.connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnback = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblDGL = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtNIC = new javax.swing.JTextField();
        lblPASS = new javax.swing.JLabel();
        lblNIC = new javax.swing.JLabel();
        btnLOGIN = new javax.swing.JButton();
        pfPASS = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnback.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Documents\\NetBeansProjects\\BCMS\\images\\left-arrow.png")); // NOI18N
        btnback.setText("Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        jPanel1.add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Documents\\NetBeansProjects\\BCMS\\images\\bg8.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, -100, 570, 980));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Documents\\NetBeansProjects\\BCMS\\images\\grasss.png")); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 760, 580, 300));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 1090));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDGL.setBackground(new java.awt.Color(255, 255, 255));
        lblDGL.setFont(new java.awt.Font("Times New Roman", 1, 85)); // NOI18N
        lblDGL.setForeground(new java.awt.Color(255, 255, 255));
        lblDGL.setText("Department Officer Login");
        jPanel2.add(lblDGL, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, -1, -1));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51,150));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNIC.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txtNIC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNICActionPerformed(evt);
            }
        });
        jPanel3.add(txtNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 350, 60));

        lblPASS.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lblPASS.setForeground(new java.awt.Color(255, 255, 255));
        lblPASS.setText("Password");
        jPanel3.add(lblPASS, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        lblNIC.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lblNIC.setForeground(new java.awt.Color(255, 255, 255));
        lblNIC.setText("NIC");
        jPanel3.add(lblNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        btnLOGIN.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnLOGIN.setText("Login");
        btnLOGIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLOGINActionPerformed(evt);
            }
        });
        jPanel3.add(btnLOGIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 130, 50));

        pfPASS.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        pfPASS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfPASSActionPerformed(evt);
            }
        });
        jPanel3.add(pfPASS, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 350, 60));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, 620, 420));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Documents\\NetBeansProjects\\BCMS\\images\\pin8.jpg")); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, -4, 1400, 1090));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 1400, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLOGINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLOGINActionPerformed
        // TODO add your handling code here:
                try{
                    String sql = "Select * from departmentofficer where nic=? and password=?";
                    PreparedStatement pst = con.prepareStatement(sql);
                    pst.setString(1,txtNIC.getText());
                    pst.setString(2,pfPASS.getText());
                    ResultSet rs =pst.executeQuery();
                    if(rs.next()){
                        JOptionPane.showMessageDialog(null,"NIC and Password Matched");
                        addbirdwatcher abw = new addbirdwatcher();
                        abw.setVisible(true);
                        setVisible(false);
                    }else{
                        JOptionPane.showMessageDialog(null,"Incorrect NIC or Password");
                        txtNIC.setText("");
                        pfPASS.setText("");
                    }con.close();
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null,e);
                }
    }//GEN-LAST:event_btnLOGINActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        this.toBack();
        Login lg = new Login();
        lg.setVisible(true);
        lg.toFront();
        this.hide();
    }//GEN-LAST:event_btnbackActionPerformed

    private void txtNICActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNICActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNICActionPerformed

    private void pfPASSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfPASSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfPASSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(department_officer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(department_officer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(department_officer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(department_officer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new department_officer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLOGIN;
    private javax.swing.JButton btnback;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblDGL;
    private javax.swing.JLabel lblNIC;
    private javax.swing.JLabel lblPASS;
    private javax.swing.JPasswordField pfPASS;
    private javax.swing.JTextField txtNIC;
    // End of variables declaration//GEN-END:variables
}
