/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lenovo
 */
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
public class director_genaral_dashb extends javax.swing.JFrame {
    Connection con;
    PreparedStatement pst;
    /**
     * Creates new form director_genaral_dashb
     */
    public director_genaral_dashb() {
        initComponents();
        con= SQLCON.connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDGD = new javax.swing.JTable();
        btnviewdata = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblDGD.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tblDGD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Scientific Name", "Colour", "Size", "Population"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDGD.setFocusable(false);
        tblDGD.setGridColor(new java.awt.Color(255, 255, 255));
        tblDGD.setRowHeight(25);
        tblDGD.setRowMargin(5);
        jScrollPane2.setViewportView(tblDGD);
        if (tblDGD.getColumnModel().getColumnCount() > 0) {
            tblDGD.getColumnModel().getColumn(0).setResizable(false);
            tblDGD.getColumnModel().getColumn(0).setPreferredWidth(5);
            tblDGD.getColumnModel().getColumn(1).setResizable(false);
            tblDGD.getColumnModel().getColumn(2).setResizable(false);
            tblDGD.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 1300, 530));

        btnviewdata.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnviewdata.setText("View Data");
        btnviewdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewdataActionPerformed(evt);
            }
        });
        jPanel1.add(btnviewdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(1410, 330, 140, 40));

        btnback.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Documents\\NetBeansProjects\\BCMS\\images\\left-arrow.png")); // NOI18N
        btnback.setText("Back");
        btnback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbackMouseClicked(evt);
            }
        });
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        btnback.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnbackKeyPressed(evt);
            }
        });
        jPanel1.add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 110, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Documents\\NetBeansProjects\\BCMS\\images\\pin2.jpg")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1920, 1120));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        this.toBack();
        Login lg = new Login();
        lg.setVisible(true);
        lg.toFront();
        this.hide();
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnviewdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewdataActionPerformed
        try{
            Statement st=con.createStatement();

            String sql="SELECT * FROM bird;";
            ResultSet rs=st.executeQuery(sql);

            while(rs.next()){
                String sciencename = rs.getString("scientific_name");
                String colour = rs.getString("colour");
                String size = rs.getString("size");
                String population = rs.getString("population");
                String tbData[] = {sciencename,colour,size,population};

                DefaultTableModel tbModel = (DefaultTableModel)tblDGD.getModel();
                tbModel.addRow(tbData);
            }
            con.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_btnviewdataActionPerformed

    private void btnbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbackMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnbackMouseClicked

    private void btnbackKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnbackKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnbackKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(director_genaral_dashb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(director_genaral_dashb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(director_genaral_dashb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(director_genaral_dashb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new director_genaral_dashb().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnviewdata;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblDGD;
    // End of variables declaration//GEN-END:variables
}
