/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Manuja
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnBirdWLogin = new javax.swing.JButton();
        btnDOLogin = new javax.swing.JButton();
        btnDGLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home Page");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 80)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Birds Conservation  ");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 60, 930, 110));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 80)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Management System");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, 960, 110));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204,120));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBirdWLogin.setBackground(new java.awt.Color(204, 204, 204));
        btnBirdWLogin.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        btnBirdWLogin.setText("Bird Watcher Login");
        btnBirdWLogin.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 255, 153)));
        btnBirdWLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBirdWLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBirdWLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnBirdWLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 54, 410, 80));

        btnDOLogin.setBackground(new java.awt.Color(204, 204, 204));
        btnDOLogin.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        btnDOLogin.setText("Department Officer Login");
        btnDOLogin.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 255, 153)));
        btnDOLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDOLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDOLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnDOLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 420, 80));

        btnDGLogin.setBackground(new java.awt.Color(204, 204, 204));
        btnDGLogin.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        btnDGLogin.setText("Director General Login");
        btnDGLogin.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 255, 153)));
        btnDGLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDGLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDGLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnDGLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 410, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 520, 450));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Documents\\NetBeansProjects\\BCMS\\images\\6.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -60, 1920, 1190));

        setSize(new java.awt.Dimension(1938, 1127));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBirdWLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBirdWLoginActionPerformed
        // TODO add your handling code here:
        BirdWatcherLogin ad = new BirdWatcherLogin();
        ad.show();
        this.hide();
        
    }//GEN-LAST:event_btnBirdWLoginActionPerformed

    private void btnDOLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDOLoginActionPerformed
        // TODO add your handling code here:
        department_officer DO = new department_officer();
        DO.show();
        this.hide();
    }//GEN-LAST:event_btnDOLoginActionPerformed

    private void btnDGLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDGLoginActionPerformed
        // TODO add your handling code here:
        directer_genaral_loginpage dg = new directer_genaral_loginpage();
        dg.show();
        this.hide();
        
    }//GEN-LAST:event_btnDGLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBirdWLogin;
    private javax.swing.JButton btnDGLogin;
    private javax.swing.JButton btnDOLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
